name: Pomander
pygments: true
permalink: /:title

navigation:
- title: Getting Started
  url: getting-started.html
- title: Settings
  url: settings.html
- title: Tasks
  url: tasks.html
- title: Wordpress Plugin
  url: wordpress.html
