development: &defaults
  url: dev.local
  user: cap
  repository: cap@git.msltechdev.com:vpsi/wordpress.git
  revision: 
  deploy_to:
  backup: false
  app:
  db:
  wordpress:
    version: 3.2.1
    db: wp_vpsi
    db_user: root
    db_password:
    db_host: localhost
    db_prefix: wp_
    db_charset: utf8
    base_uri: 
staging:
  <<:   *defaults
  user: cap
  deploy_to: /msl/php/vpsi
  app:
    - stage1.mslideas.com
  db:
    - stage1.mslideas.com
production:
  <<:   *defaults
  user: cap
  deploy_to: /msl/php/TESTING
  revision: origin/master
  app:
    - web-01.mslideas.com
    - web-02.mslideas.com
  db:
    - web-01.mslideas.com
  wordpress:
    version: 3.2.1
    db: JUST_TESTING
    db_user: vanpools
    db_password: vanpools!
    db_host: vip-db
    db_prefix: wp_
    db_charset: utf8
    base_uri:
