development:
  url: dev.local
  user: cap
  repository: cap@git.msltechdev.com:vpsi/wordpress.git
  deploy_to: /Users/mkruk/Sites/php/vpsi
  backup: false
  app:
    - stage1.mslideas.com
  db:
    - stage1.mslideas.com
  wordpress:
    version: 3.2.1
    db: wp_vpsi
    db_user: root
    db_password:
    db_host: localhost
    db_prefix: wp_
    db_charset: utf8
    base_uri: 
staging:
  user: cap
  deploy_to: /msl/php/vpsi
  app:
    - stage1.mslideas.com
  db:
    - stage1.mslideas.com
production:
  user: cap
  deploy_to: /msl/php/vpsi
  app:
    - web-01.mslideas.com
    - web-02.mslideas.com
  db:
    - web-01.mslideas.com
